-- GMS Catalogue Management System
-- Authentication tables for PostgreSQL / pgAdmin 4
--
-- This script is idempotent: it can be executed more than once.
-- Passwords must be created through the FastAPI administrator script so they
-- are stored as Argon2 hashes, never as plain text.

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS roles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username VARCHAR(80) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    full_name VARCHAR(160) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    failed_login_attempts INTEGER NOT NULL DEFAULT 0,
    locked_until TIMESTAMPTZ NULL,
    last_login_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_users_username_lower
    ON users (LOWER(username));

CREATE UNIQUE INDEX IF NOT EXISTS ix_users_email_lower
    ON users (LOWER(email));

CREATE TABLE IF NOT EXISTS user_roles (
    user_id UUID NOT NULL
        REFERENCES users(id) ON DELETE CASCADE,
    role_id INTEGER NOT NULL
        REFERENCES roles(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS catalogue_audit_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NULL
        REFERENCES users(id) ON DELETE SET NULL,
    action VARCHAR(80) NOT NULL,
    module VARCHAR(80) NOT NULL DEFAULT 'authentication',
    status VARCHAR(30) NOT NULL,
    identifier VARCHAR(255) NULL,
    ip_address VARCHAR(64) NULL,
    user_agent TEXT NULL,
    details JSONB NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_audit_created_at
    ON catalogue_audit_logs (created_at);

CREATE INDEX IF NOT EXISTS ix_audit_action
    ON catalogue_audit_logs (action);

INSERT INTO roles (name, description)
VALUES
    (
        'system_user',
        'Standard catalogue portal user with permissions assigned by a superadmin.'
    ),
    (
        'superadmin',
        'Full system administrator with user, role and configuration access.'
    )
ON CONFLICT (name) DO UPDATE
SET description = EXCLUDED.description;

COMMIT;
