-- GMS Catalogue Management System
-- Catalogue-owned tables layered over the read-only ERP product snapshot.

BEGIN;

CREATE TABLE IF NOT EXISTS products (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    sku VARCHAR(80) NOT NULL UNIQUE,
    erp_name VARCHAR(255) NOT NULL,
    brand VARCHAR(120) NULL,
    barcode VARCHAR(80) NULL UNIQUE,
    unit VARCHAR(30) NOT NULL DEFAULT 'piece',
    erp_category VARCHAR(120) NULL,
    price NUMERIC(12, 2) NULL,
    stock_quantity INTEGER NOT NULL DEFAULT 0,
    is_discontinued BOOLEAN NOT NULL DEFAULT FALSE,
    erp_updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_products_erp_name ON products (erp_name);
CREATE INDEX IF NOT EXISTS ix_products_brand ON products (brand);

CREATE TABLE IF NOT EXISTS categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    slug VARCHAR(120) NOT NULL UNIQUE,
    description VARCHAR(320) NOT NULL DEFAULT '',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS product_categories (
    product_id UUID NOT NULL
        REFERENCES products(id) ON DELETE CASCADE,
    category_id INTEGER NOT NULL
        REFERENCES categories(id) ON DELETE CASCADE,
    PRIMARY KEY (product_id, category_id)
);

CREATE TABLE IF NOT EXISTS catalogue_entries (
    product_id UUID PRIMARY KEY
        REFERENCES products(id) ON DELETE CASCADE,
    display_name VARCHAR(255) NOT NULL DEFAULT '',
    short_description VARCHAR(320) NOT NULL DEFAULT '',
    long_description TEXT NOT NULL DEFAULT '',
    seo_title VARCHAR(180) NOT NULL DEFAULT '',
    seo_description VARCHAR(320) NOT NULL DEFAULT '',
    visibility VARCHAR(20) NOT NULL DEFAULT 'hidden'
        CHECK (visibility IN ('hidden', 'public')),
    workflow_status VARCHAR(30) NOT NULL DEFAULT 'draft'
        CHECK (workflow_status IN ('draft', 'in_review', 'approved', 'published')),
    is_featured BOOLEAN NOT NULL DEFAULT FALSE,
    version INTEGER NOT NULL DEFAULT 1,
    updated_by_id UUID NULL REFERENCES users(id) ON DELETE SET NULL,
    approved_by_id UUID NULL REFERENCES users(id) ON DELETE SET NULL,
    published_by_id UUID NULL REFERENCES users(id) ON DELETE SET NULL,
    submitted_at TIMESTAMPTZ NULL,
    approved_at TIMESTAMPTZ NULL,
    published_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE catalogue_entries
    ADD COLUMN IF NOT EXISTS display_name VARCHAR(255) NOT NULL DEFAULT '';

CREATE INDEX IF NOT EXISTS ix_catalogue_workflow_status
    ON catalogue_entries (workflow_status);
CREATE INDEX IF NOT EXISTS ix_catalogue_visibility
    ON catalogue_entries (visibility);
CREATE INDEX IF NOT EXISTS ix_catalogue_updated_at
    ON catalogue_entries (updated_at);

CREATE TABLE IF NOT EXISTS product_images (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    file_name VARCHAR(255) NOT NULL,
    storage_name VARCHAR(255) NOT NULL UNIQUE,
    public_url VARCHAR(500) NOT NULL,
    content_type VARCHAR(80) NOT NULL,
    alt_text VARCHAR(255) NOT NULL DEFAULT '',
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    uploaded_by_id UUID NULL REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_product_image_sort_order UNIQUE (product_id, sort_order)
);

CREATE INDEX IF NOT EXISTS ix_product_images_product
    ON product_images (product_id);

INSERT INTO roles (name, description)
VALUES
    (
        'catalogue_editor',
        'Edits catalogue content and submits changes for approval.'
    ),
    (
        'catalogue_approver',
        'Reviews, approves and publishes catalogue changes.'
    ),
    (
        'catalogue_admin',
        'Manages catalogue content, users and system configuration.'
    ),
    (
        'viewer',
        'Can view catalogue management data and reports.'
    )
ON CONFLICT (name) DO UPDATE
SET description = EXCLUDED.description;

COMMIT;
