-- Configurable price lists, price history, user permission overrides,
-- catalogue builder records and immutable published snapshots.

BEGIN;

CREATE TABLE IF NOT EXISTS user_permission_overrides (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    permission_id INTEGER NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
    is_allowed BOOLEAN NOT NULL,
    reason VARCHAR(320) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_user_permission_override UNIQUE (user_id, permission_id)
);

CREATE TABLE IF NOT EXISTS price_lists (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(40) NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL UNIQUE,
    description VARCHAR(320) NOT NULL DEFAULT '',
    currency VARCHAR(3) NOT NULL DEFAULT 'THB',
    is_no_price BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS product_prices (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    product_id UUID NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    price_list_id INTEGER NOT NULL REFERENCES price_lists(id) ON DELETE RESTRICT,
    currency VARCHAR(3) NOT NULL DEFAULT 'THB',
    amount NUMERIC(14, 2) NOT NULL CHECK (amount >= 0),
    effective_from TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    reason VARCHAR(500) NOT NULL,
    created_by_id UUID NULL REFERENCES users(id) ON DELETE SET NULL,
    approved_by_id UUID NULL REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    approved_at TIMESTAMPTZ NULL,
    CHECK (expires_at IS NULL OR expires_at > effective_from)
);

CREATE INDEX IF NOT EXISTS ix_product_prices_lookup
    ON product_prices (product_id, price_list_id, status);
CREATE INDEX IF NOT EXISTS ix_product_prices_effective
    ON product_prices (effective_from, expires_at);

CREATE TABLE IF NOT EXISTS price_change_requests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    product_id UUID NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    price_list_id INTEGER NOT NULL REFERENCES price_lists(id) ON DELETE RESTRICT,
    proposed_amount NUMERIC(14, 2) NOT NULL CHECK (proposed_amount >= 0),
    currency VARCHAR(3) NOT NULL DEFAULT 'THB',
    effective_from TIMESTAMPTZ NOT NULL,
    reason VARCHAR(500) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    requested_by_id UUID NULL REFERENCES users(id) ON DELETE SET NULL,
    reviewed_by_id UUID NULL REFERENCES users(id) ON DELETE SET NULL,
    review_reason VARCHAR(500) NOT NULL DEFAULT '',
    resulting_price_id UUID NULL REFERENCES product_prices(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_at TIMESTAMPTZ NULL
);

CREATE INDEX IF NOT EXISTS ix_price_requests_status
    ON price_change_requests (status, created_at);

CREATE TABLE IF NOT EXISTS catalogues (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title VARCHAR(220) NOT NULL,
    slug VARCHAR(240) NOT NULL UNIQUE,
    description TEXT NOT NULL DEFAULT '',
    brand VARCHAR(120) NULL,
    audience VARCHAR(120) NOT NULL DEFAULT 'Internal',
    price_list_id INTEGER NULL REFERENCES price_lists(id) ON DELETE SET NULL,
    show_prices BOOLEAN NOT NULL DEFAULT TRUE,
    currency VARCHAR(3) NOT NULL DEFAULT 'THB',
    language VARCHAR(10) NOT NULL DEFAULT 'en',
    status VARCHAR(30) NOT NULL DEFAULT 'draft',
    version INTEGER NOT NULL DEFAULT 0,
    revision INTEGER NOT NULL DEFAULT 1,
    valid_from TIMESTAMPTZ NULL,
    valid_until TIMESTAMPTZ NULL,
    is_public BOOLEAN NOT NULL DEFAULT FALSE,
    owner_id UUID NULL REFERENCES users(id) ON DELETE SET NULL,
    created_by_id UUID NULL REFERENCES users(id) ON DELETE SET NULL,
    updated_by_id UUID NULL REFERENCES users(id) ON DELETE SET NULL,
    published_by_id UUID NULL REFERENCES users(id) ON DELETE SET NULL,
    published_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (valid_until IS NULL OR valid_from IS NULL OR valid_until > valid_from)
);

CREATE INDEX IF NOT EXISTS ix_catalogues_status_updated
    ON catalogues (status, updated_at);

CREATE TABLE IF NOT EXISTS catalogue_products (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    catalogue_id UUID NOT NULL REFERENCES catalogues(id) ON DELETE CASCADE,
    product_id UUID NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    section_title VARCHAR(180) NOT NULL DEFAULT '',
    override_description TEXT NOT NULL DEFAULT '',
    hide_price BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order INTEGER NOT NULL,
    CONSTRAINT uq_catalogue_product UNIQUE (catalogue_id, product_id),
    CONSTRAINT uq_catalogue_sort_order UNIQUE (catalogue_id, sort_order)
);

CREATE TABLE IF NOT EXISTS catalogue_versions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    catalogue_id UUID NOT NULL REFERENCES catalogues(id) ON DELETE CASCADE,
    version_number INTEGER NOT NULL,
    snapshot JSONB NOT NULL,
    published_by_id UUID NULL REFERENCES users(id) ON DELETE SET NULL,
    published_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_catalogue_version UNIQUE (catalogue_id, version_number)
);

CREATE INDEX IF NOT EXISTS ix_catalogue_versions_published
    ON catalogue_versions (published_at);

INSERT INTO price_lists (code, name, description, currency, is_no_price)
VALUES
    ('NORMAL', 'Normal', 'Standard customer price list.', 'THB', FALSE),
    ('VIP', 'VIP', 'Preferred VIP customer pricing.', 'THB', FALSE),
    ('BIG_CUSTOMER', 'Big Customer', 'Large customer account pricing.', 'THB', FALSE),
    ('DEALER', 'Dealer', 'Authorized dealer pricing.', 'THB', FALSE),
    ('WHOLESALE', 'Wholesale', 'Wholesale channel pricing.', 'THB', FALSE),
    ('RETAIL', 'Retail', 'Retail channel pricing.', 'THB', FALSE),
    ('NO_PRICE', 'No Price', 'Catalogue without monetary values.', 'THB', TRUE)
ON CONFLICT (code) DO NOTHING;

COMMIT;
